name:                TimeAttendance
version:             0.1.0.0
github:              "githubuser/TimeAttendance"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/TimeAttendance#readme>

dependencies:
- base >= 4.7 && < 5
- time >= 1.8.0.2
- hspec >= 2.5.5
- QuickCheck >= 2.11.3

library:
  source-dirs: src

executables:
  TimeAttendance-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - TimeAttendance

tests:
  TimeAttendance-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - TimeAttendance
